version: "3.8"
services:
  app:
    image: jc21/nginx-proxy-manager:latest
    container_name: npm
    restart: unless-stopped
    ports:
      - "80:80"     # HTTP
      - "81:81"     # Web UI của NPM
      - "443:443"   # HTTPS
      - "2222:2222" # SSH
      - "10000-11000:10000-11000"
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
